---
- name: Pull and Run docker image
  hosts: all
  tasks:
    - name: copy docker compose file from folder to remote host
      copy:
        src: ./docker-compose.yml
        dest: ./
    - name: pull images specifed in docker-compose
      command: docker-compose -f ./docker-compose.yml pull
    - name: run the pulled docker images in detached mode
      command: docker-compose -f ./docker-compose.yml up -d